name: PR Test

on:
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run type-check
        run: npm run type-check

      - name: Run lint
        run: npm run lint

      - name: Run test
        run: npm run test
